apply plugin: 'com.android.library'
apply plugin: 'com.github.dcendents.android-maven'
apply plugin: 'com.jfrog.bintray'
group = publishedGroupId
version = libraryVersion
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.github.dcendents:android-maven-gradle-plugin:1.4.1'
        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.7.3'
    }
}
android {
    compileSdk=34
    defaultConfig {
        minSdk=26
        targetSdk=34
        versionCode 1
        versionName "3.0.1-beta.2"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        buildConfigField 'String', 'SIP_DOMAIN', '"phone.plivo.com"'
        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    packagingOptions {
        exclude 'META-INF/proguard/androidx-annotations.pro'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    // Removed deprecated Android Support library - using AndroidX in main build.gradle instead
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'org.mockito:mockito-core:2.6.8'
    androidTestImplementation 'com.linkedin.dexmaker:dexmaker-mockito:2.2.0'
    androidTestImplementation 'com.google.truth:truth:0.42'
//    androidTestImplementation 'com.google.truth.extensions:truth-java8-extension:0.42'
    androidTestImplementation "androidx.test.ext:junit:1.0.0"
    androidTestImplementation 'androidx.test:rules:1.1.0'
}
apply from: 'maven.gradle'
